<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Análise de Dados: Fundamentos de Estatística
Caderno de **Exercícios**<br> 
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Média e Variância;</li>
  <li>Ordem e Posição;</li>
  <li>Correlação.</li>
</ol>

---

# **Exercícios**

## 1\. Tráfego de São Paulo

Neste exercício, vamos continuar a analisar os dados de mobilidade urbana da cidade de São Paulo. A base de dados está neste [link](https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/develop/dataset/traffic.csv) e é uma copia do dado original, presente neste [link](https://archive.ics.uci.edu/ml/datasets/Behavior+of+the+urban+traffic+of+the+city+of+Sao+Paulo+in+Brazil). A base de dados contem a quantidade de acidentes ocorridos na cidade entre 14/12/09 e 18/12/09, das 07:00h ás 20:00h, agregados em intervalos de 30 minutos.

In [1]:
!wget -q "https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/develop/dataset/traffic.csv" -O traffic.csv

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('traffic.csv', sep=';')

In [7]:
df.head(28)

,hour,bus_stoped,broken_truck,vehicle_excess,accident_victim,running_over,fire_vehicles,occurrence_freight,incident__dangerous_freight,lack_electricity,fire,flooding,manifestations,defect_trolleybuses,tree_road,semaphore_off,intermittent_emaphore,slowness_traffic_%
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"4,1"
1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"6,6"
2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"8,7"
3,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"9,2"
4,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"11,1"
5,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"10,9"
6,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"8,3"
7,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"8,2"
8,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"7,6"
9,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"6,4"
10,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"5,2"
11,12,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"4,7"
12,13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"4,8"
13,14,2,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,"4,9"
14,15,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"5,1"
15,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"5,3"
16,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"6,9"
17,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"5,1"
18,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"6,7"
19,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"8,1"
20,21,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"9,5"
21,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"9,4"
22,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"9,9"
23,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"11,2"
24,25,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,"11,8"
25,26,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,"11,4"
26,27,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,"7,4"
27,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,"4,9"

In [8]:

df.shape

(135, 18)

- **Exemplo**: (para relembrar)

O código abaixo extrai a 13ª linha do arquivo que representa a 14ª meia hora do dia 14/12/09, contadas a partir das 07:00h, ou seja, todos os incidentes ocorridos na cidade no dia em questão entre as 13:30h e 14:00h. Vemos, por exemplo, que dois ônibus e dois caminhões ficaram paradados nas ruas da cidade, atrapalhando o tráfego.

In [6]:
df.iloc[[13]]

,hour,bus_stoped,broken_truck,vehicle_excess,accident_victim,running_over,fire_vehicles,occurrence_freight,incident__dangerous_freight,lack_electricity,fire,flooding,manifestations,defect_trolleybuses,tree_road,semaphore_off,intermittent_emaphore,slowness_traffic_%
13,14,2,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,"4,9"

### **1.1. Agregação**

Neste primeira atividade, você deve gerar um array NumPy por dia. Para cada array você deve somar todos os incidentes que aconteceram naquela meia hora. Sendo assim, cada array deve ter 27 posições, cada qual com a soma dos incidentes daquela meira hora.

**Dica**: Você deve remover a primeira e a última coluna.

**Dica**: Os arrays devem ter os seguintes valores:

```python
14: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 2, 3]
15: [3, 0, 0, 0, 2, 4, 2, 1, 3, 0, 2, 0, 2, 3, 2, 2, 4, 7, 6, 3, 0, 1, 1, 5, 4, 6, 0]
16: [1, 1, 2, 4, 4, 5, 3, 2, 4, 2, 1, 1, 3, 6, 2, 0, 2, 8, 4, 6, 4, 1, 2, 7, 15, 4, 0]
17: [4, 1, 1, 0, 0, 0, 2, 3, 2, 7, 2, 1, 7, 3, 6, 4, 3, 2, 2, 3, 2, 5, 2, 0, 1, 4, 15]
18: [10, 1, 1, 5, 5, 7, 3, 4, 3, 1, 2, 3, 2, 2, 6, 2, 2, 4, 2, 3, 0, 3, 3, 2, 3, 6, 0]
```

In [9]:
# resposta da questão 1.1


import numpy as np

data = []

with open(file='traffic.csv', mode='r', encoding='utf8') as fp:
  
  fp.readline()
  data = fp.read()

day = 14
incidents = 0
incident_by_day = dict()
vector = list()

for timebox in data.split(sep='\n'):

  timebox_data = timebox.split(sep=';')
  incidents = np.sum(np.array(timebox_data[1: len(timebox_data)-1], dtype = 'int64'))
  vector.append(incidents)
  incidents = 0
  try: 

    half_hour = int(timebox_data[0])

    if half_hour == 27:
       
       incident_by_day[day] = vector
       day = day + 1
       vector = list()
  
  except ValueError:
    continue

for day in incident_by_day:
  
  print(f'{day}: {incident_by_day[day]}')

14: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 2, 3]
15: [3, 0, 0, 0, 2, 4, 2, 1, 3, 0, 2, 0, 2, 3, 2, 2, 4, 7, 6, 3, 0, 1, 1, 5, 4, 6, 0]
16: [1, 1, 2, 4, 4, 5, 3, 2, 4, 2, 1, 1, 3, 6, 2, 0, 2, 8, 4, 6, 4, 1, 2, 7, 15, 4, 0]
17: [4, 1, 1, 0, 0, 0, 2, 3, 2, 7, 2, 1, 7, 3, 6, 4, 3, 2, 2, 3, 2, 5, 2, 0, 1, 4, 15]
18: [10, 1, 1, 5, 5, 7, 3, 4, 3, 1, 2, 3, 2, 2, 6, 2, 2, 4, 2, 3, 0, 3, 3, 2, 3, 6, 0]

### **1.2. Métricas**

Para cada array você deve calcular as seguintes métricas: 

 - **média**;
 - **desvio padrão**.

In [15]:
# resposta da questão 1.2

In [10]:

# Média e desvio padrão do dia 14:

mean_day_14 = np.mean(incident_by_day[14])
std_day_14 = np.std(incident_by_day[14])

print(f'A média do dia 14 é: ', mean_day_14)
print(f'O desvio padrão do dia 14 é: ', std_day_14)

A média do dia 14 é:  0.5925925925925926
O desvio padrão do dia 14 é:  1.1944085553034889

In [11]:
# Média e desvio padrão do dia 15:

mean_day_15 = np.mean(incident_by_day[15])
std_day_15 = np.std(incident_by_day[15])

print(f'A média do dia 15 é: ', mean_day_15)
print(f'O desvio padrão do dia 15 é: ', std_day_15)

A média do dia 15 é:  2.3333333333333335
O desvio padrão do dia 15 é:  2.0184335693983275

In [12]:

# Média e desvio padrão do dia 16:

mean_day_16 = np.mean(incident_by_day[16])
std_day_16 = np.std(incident_by_day[16])

print(f'A média do dia 16 é: ', mean_day_16)
print(f'O desvio padrão do dia 16 é: ', std_day_16)

A média do dia 16 é:  3.4814814814814814
O desvio padrão do dia 16 é:  3.047407767514698

In [13]:
# Média e desvio padrão do dia 17:

mean_day_17 = np.mean(incident_by_day[17])
std_day_17 = np.std(incident_by_day[17])

print(f'A média do dia 17 é: ', mean_day_17)
print(f'O desvio padrão do dia 17 é: ', std_day_17)

A média do dia 17 é:  3.037037037037037
O desvio padrão do dia 17 é:  3.0487578707046925

In [14]:

# Média e desvio padrão do dia 18:

mean_day_18 = np.mean(incident_by_day[18])
std_day_18 = np.std(incident_by_day[18])

print(f'A média do dia 18 é: ', mean_day_18)
print(f'O desvio padrão do dia 18 é: ', std_day_18)

A média do dia 18 é:  3.1481481481481484
O desvio padrão do dia 18 é:  2.1892617342417258

### **1.3. Interpretação**

Baseado nos resultados da questão 1.2, responda:

> Qual dia apresenta a maior média de acidentes por meia hora?

**Resposta:** O dia 16 apresenta a maior média de acidentes por meia hora, com um resultado de aproximadamente 3,48.

> Qual dia apresenta a menor variação de acidentes por meia hora?

**Resposta:** O dia 14 apresenta a menor variação de acidentes por meia hora, com um resultado de aproximadamente 1,19.

---